# Generated by Django 2.2b1 on 2019-03-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image_upload')),
                ('user', models.ManyToManyField(related_name='_postimage_user_+', to='blog.PostImage')),
            ],
        ),
    ]
