# Generated by Django 2.2b1 on 2019-03-14 06:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_transaction', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('item', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=4)),
                ('rate', models.DecimalField(decimal_places=3, max_digits=4)),
                ('principle', models.DecimalField(decimal_places=3, max_digits=8)),
                ('interest', models.DecimalField(decimal_places=3, max_digits=8)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
        ),
    ]
