# Generated by Django 2.2b1 on 2019-03-14 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Mortgage',
        ),
    ]
