# Generated by Django 2.1.7 on 2019-03-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0002_auto_20190314_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mortgage',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=19),
        ),
        migrations.AlterField(
            model_name='mortgage',
            name='principle',
            field=models.DecimalField(decimal_places=3, max_digits=19),
        ),
    ]
